"""empty message

Revision ID: 587ca82d93fd
Revises: 8c0a7ff79460
Create Date: 2022-02-17 12:15:26.868391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587ca82d93fd'
down_revision = '8c0a7ff79460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['author'], ['id'])
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###
